### PR TITLE
Add security rules from mozfreddyb/eslint-config-scanjs

### PR DESCRIPTION
**Pull request by g-k**
Pulls in security lint checks from B2G that might be helpful.

Due to https://github.com/eslint/eslint/issues/3458 we'd need to add `eslint-plugin-no-unsafe-innerhtml` and `eslint-plugin-scanjs-rules` as devDependencies to projects using this config.

We could limit this to the client config if templates aren't rendered server side and disable some of the more verbose warnings like `setTimeout` and `setInterval` and B2G specific warnings.

smoke test:

```sh
fxa-local-dev/fxa-customs-server $ npm link ~/eslint-config-fxa  # on this branch
fxa-local-dev/fxa-customs-server $ npm install -D eslint-plugin-no-unsafe-innerhtml
fxa-local-dev/fxa-customs-server $ npm install -D eslint-plugin-scanjs-rules
fxa-local-dev/fxa-customs-server $ # add foo.innerHTML = input.value to lib/actions.js
fxa-local-dev/fxa-customs-server $ node_modules/.bin/grunt lint
Running "eslint:files" (eslint) task

/Users/gguthe/fxa-local-dev/fxa-customs-server/lib/actions.js
  13:1   error  Unsafe assignment to innerHTML  no-unsafe-innerhtml/no-unsafe-innerhtml
  13:1   error  'foo' is not defined            no-undef
  13:17  error  'input' is not defined          no-undef

/Users/gguthe/fxa-local-dev/fxa-customs-server/lib/allowed_email_domains.js
  50:20  warning  The function setInterval can be unsafe  scanjs-rules/call_setInterval
...
```

### CODE REVIEW

**Comment by pdehaan** [comment]
This seem to cause a very high number of false positives on the fxa-content-server repo, which means we'd either need to exclude a bunch of these rules by adding a handful of nested .eslintrc files in ./test/, ./app/test/, ./grunttasks/, and ./app/.

Even after adding all the rules to the new places (if I don't care about /tests/ or /app/tests/ usages, for example), I still have about 46 instances in the code base that I'd need to add "eslint-disable-line scanjs-rules/call_setImmedate" throughout the code, which is pretty tedious, or else need to just audit each usage and add a global ignore in the root .eslintrc file.

**Comment by pdehaan** [comment]
@g-k: Actually, how would we feel about just using something like this config? https://github.com/jkohrman/eslint-config-secure

And then in fxa-content-server's .eslintrc.yml (or wherever), we could just do this to shim in the secure rules:

``` yaml
extends:
  - eslint:recommended
  - fxa/client
  - secure
```

Makes it a bit easier to toggle the rules on and off instead of needing to resort to adding `// eslint-disable-line scanjs-rules/call_writeln` everywhere.

**Comment by pdehaan** [comment]
I guess conversely, we could move all these rules into a "secure.js" and then people could extend "fxa", "fxa/client", "fxa/server", and/or "fxa/secure" from this config.

---

**UPDATE:** PR for this approach at #9

**Comment by g-k** [comment]
@pdehaan nice!  It's clearer to have a separate config for non-style related checks.

We can probably disable a bunch of the scanjs checks if they're throwing a bunch of false positives.

FWIW this isn't a pressing security issue or anything just something ulfr wanted me to get people thinking about.

Closing this PR in favor of either of the above approaches.

**Comment by g-k** [comment]
@pdehaan Freddy said:

> I see most of the scanjs-rules did not make it into FxA and I strongly recommend not using them for linting. They are really useful for half-automated/manual testing and identifying critical code paths, but they generate lots of false positives, because they are really not sophisticated).
> 
> The no-unsafe-innerhtml thing is a completely different beast. I strongly recommend using it and it is very much worth the effort!

**Pull request closed without merging**
